{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  dnsNames:
  - {{ .Values.certificate.dnsName }}
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ .Values.certificate.issuerRef.name }}
  secretName: {{ .Values.certificate.secretName }}
  privateKey:
    rotationPolicy: {{ .Values.certificate.privateKey.rotationPolicy }}
  usages:
  - server auth
  - client auth
  - digital signature
  keystores:
    jks:
      create: {{ .Values.certificate.keystores.jks.create }}
      password: {{ .Values.certificate.keystores.jks.password }}
    pkcs12:
      create: {{ .Values.certificate.keystores.pkcs12.create }}
      password: {{ .Values.certificate.keystores.pkcs12.password }}
{{- end }}
