apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}-environment
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
{{- if  .Values.config.configFilesGlob}}
binaryData:
{{- range $path, $_ :=  .Files.Glob .Values.config.configFilesGlob }}
{{ $path | base | indent 2 }}: |-
{{ $.Files.Get $path | b64enc | indent 4 }}
{{- end }}
{{- else }}
{{- if or .Values.config.inline .Values.config.inlineData }}
data:
{{- end }}
{{- if .Values.config.inline }} {{/* check inline for backwards compatibility */}}
{{.Values.config.inline | indent 2}}
{{- end }}
{{- if .Values.config.inlineData }}
{{.Values.config.inlineData | indent 2}}
{{- end }}
{{- if .Values.config.inlineBinaryData }}
binaryData:
{{.Values.config.inlineBinaryData | indent 2}}
{{- end }}
{{- end }}
