apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nsi-safnari.fullname" . }}-{{ .Values.config.name }}
#  namespace: {{ .Release.Namespace }}
binaryData:
{{ range $path, $_ :=  .Files.Glob  .Values.config.configFilesGlob }}
{{ $path | base | indent 2 }}: |-
{{ $.Files.Get $path | b64enc | indent 4 }}
{{ end }}
