# .github/workflows/dependency-graph.yml
name: Update Dependency Graph
on:
  push:
    branches:
      - master # default branch of the project
  workflow_dispatch:

permissions:
  contents: write # for dependency graph upload

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Install JVM 21 + sbt
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:21
          apps: sbt
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: SBT dependency submission
        uses: scalacenter/sbt-dependency-submission@v3
