# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Start PostgreSQL
      run: sudo systemctl start postgresql.service
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Initialize PostgreSQL database
      run: |
        sudo -u postgres -i createuser -D -R -S nsi-safnari-user
        sudo -u postgres -i psql -c "ALTER USER \"nsi-safnari-user\" WITH PASSWORD 'password'"
        sudo -u postgres -i createdb -O nsi-safnari-user nsi-safnari-dev
        sudo -u postgres -i createdb -O nsi-safnari-user nsi-safnari-test
    - name: Run tests
      run: sbt test
