# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Start PostgreSQL
      run: sudo systemctl start postgresql.service
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install JVM 21 + sbt
      uses: coursier/setup-action@v1
      with:
        jvm: temurin:21
        apps: sbt
    - name: Initialize PostgreSQL database
      run: |
        sudo -u postgres -i createuser -D -R -S nsi-safnari-user
        sudo -u postgres -i psql -c "ALTER USER \"nsi-safnari-user\" WITH PASSWORD 'password'"
        sudo -u postgres -i createdb -O nsi-safnari-user nsi-safnari-dev
        sudo -u postgres -i createdb -O nsi-safnari-user nsi-safnari-test
    - name: Run tests
      run: sbt test
    - name: Check code formatting
      run: sbt scalafmtCheckAll scalafmtSbtCheck
